ALTER TABLE `user`
    ADD COLUMN role VARCHAR(16) NOT NULL DEFAULT 'STUDENT' AFTER password,
    ADD COLUMN display_name VARCHAR(64) NULL,
    ADD COLUMN avatar_url VARCHAR(512) NULL,
    ADD COLUMN college VARCHAR(128) NULL,
    ADD COLUMN grade VARCHAR(32) NULL,
    ADD COLUMN major VARCHAR(128) NULL,
    ADD COLUMN class_name VARCHAR(64) NULL,
    ADD COLUMN phone VARCHAR(32) NULL,
    ADD COLUMN email VARCHAR(128) NULL,
    ADD COLUMN job_title VARCHAR(64) NULL;
